<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Models.cs" Link="Models.cs" />
    <Compile Include="..\InputMatcher.cs" Link="InputMatcher.cs" />
    <Compile Include="..\HistoryExporter.cs" Link="HistoryExporter.cs" />
  </ItemGroup>
</Project>
